version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Vue CLI...
      - npm install -g @vue/cli
      - npm install -g @vue/cli-service
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  files:
    - dist/**/*